### ISSUE TITLE
Version discrepancy

### ISSUE THREAD

**Issue by msoub** [googleapis/java-document-ai#135]
Hello,

I get different results with the form parsing between the `processDocument`, `batchProcessDocumentsAsync` and [the demo version](https://cloud.google.com/solutions/document-ai).
Is there a version discrepancy that could explain this behaviour?

I'd like to share with you the PDF that highlights this problem but it's confidential.

Thanks for your help.

Client version: 0.2.0

**Comment by telpirion** [comment]
Thank you for filing this issue. The most recent version of Document AI, `v1beta3`, introduces the concept of [processors](https://cloud.google.com/document-ai/docs/processor-overview), which could address the inconsistency that you're experiencing.
