### ISSUE TITLE
Unit testing guidelines/flexibility

### ISSUE THREAD

**Issue by cholojuanito** [googleapis/java-document-ai#765]
**Is your feature request related to a problem? Please describe.**
It isn't possible to mock/spy the client objects in this library. This is because either all their methods are `final` methods or they don't have a `NoArgsConstructor`. (Have to use `DocumentProcessorServiceClient.create()`)

**Describe the solution you'd like**
Give some guidance or flexibility with classes like `DocumentProcessorServiceClient` so that we can unit test the code we write that uses it without actually calling the service

**Comment by kweinmeister** [comment]
I believe that you can mock final classes and methods starting in v2 of Mockito: https://www.baeldung.com/mockito-final

**Comment by cholojuanito** [comment]
After some more searching on the main GCP Java clients repo. I found this answer

https://github.com/googleapis/google-cloud-java/issues/2423#issuecomment-330936389, which recommends mocking the client stub classes. And doing that worked for me.
