### ISSUE TITLE
Code does not support displaying form data containing spaces between text

### ISSUE THREAD

**Issue by towa-fotso** [googleapis/java-document-ai#835]
Text having spaces are skipped when using the code given. I will be sending the image i passed to the form parser processor.
![0607221336~2](https://user-images.githubusercontent.com/52493904/173127559-a8c817fa-1c65-4f94-9666-cfe138df27a2.jpg)

**Comment by matthewayne** [comment]
@towa-fotso Can you please provide:

1. the code you are using to call the Document AI API
2. the expected result of running this code
3. the actual result of running this code

Please also include 
1. what fields of the Document API response you are using 
2. example data (e.g. example strings that you'd expect with the API to include, and what is actually present in the API response)

**Comment by matthewayne** [comment]
Closing for now, please reopen or create a new issue with the requested information if you're still having this issue
